#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

cd "$(dirname "$0")/.."

TEMPLATE="templates/preview-template-template.html"
OUTPUT="templates/preview-template.html"

CSS="$(script/get-github-markdown-css | sed '2,$s/^/      /' | sed 's/ *$//')"

# shellcheck disable=SC2016
export CSS && envsubst '${CSS}' < "$TEMPLATE" > "$OUTPUT"
